name: Build and deploy ASP.NET Core API app to Azure Web App

env:
  AZURE_WEBAPP_NAME: anheu-code-generator    # Set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: 'CodeGenerator.API'  # Path to your web app project
  DOTNET_VERSION: '8'  # Set this to the .NET version you are using

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build CodeGenerator.API/CodeGenerator.API.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish CodeGenerator.API/CodeGenerator.API.csproj --configuration Release --output ${{ github.workspace }}/publish

      - name: List published files
        run: ls -R ${{ github.workspace }}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-api
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-api

      - name: List files in artifact
        run: ls -R

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish
